### ISSUE TITLE
Missing attributes in models

### ISSUE THREAD

**Issue by lauracoding7** [Fitog4/rvnb#5]
- [x] we miss the attribute 'number of travelling seats' in our Rv model
- [x] we miss the attribute 'number of beds' in our Rv model
- [x] we miss the attribute 'available_in' in our Rv model
- [x] we miss the attribute 'available_from' in our Rv model
- [x] we miss the attribute 'available_till' in our Rv model

**Comment by Fitog4** [comment]
I will make them all mandatory through validations

**Comment by Fitog4** [comment]
here is my proposal to fix it https://github.com/Fitog4/rvnb/pull/7
